fix: patch for node-js-mobile
digidem/comapeo-mobile pull request #614
Opened 2024-08-19 19:44 UTC by ErikSin

Patches `nodejs-mobile-react-native` to use `mavenCentral` instead of `jcenter` as [`jcenter` is now deprecated.](https://jfrog.com/blog/jcenter-sunset/)

See https://github.com/nodejs-mobile/nodejs-mobile-react-native/issues/80

2024-08-19 19:47 UTC, achou11 requested changes
Should add an entry in the patches README too

2024-08-19 19:47 UTC, achou11 commented on patches/nodejs-mobile-react-native+18.17.7+001+jcenter-to-maven.patch
rename to `patches/nodejs-mobile-react-native+18.17.7+007+jcenter-to-maven.patch` (patch package uses that `007` to determine ordering of patches, but also helpful for documentation purposes)

2024-08-19 19:47 UTC, achou11 commented on patches/nodejs-mobile-react-native+18.17.7+001+jcenter-to-maven.patch
> + }
nit: add an empty line at the end (consistent with how the other patch files are formatted)

2024-08-19 19:58 UTC, achou11 approved these changes

2024-08-19 19:59 UTC, merged

2024-08-21 09:31 UTC, staltz commented
Hi, just to let you know that nodejs-mobile-react-native 18.17.8 was just now released with this patch incorporated. :heart: