Feat/audio error handling
digidem/comapeo-mobile pull request #782
Opened 2024-10-08 15:52 UTC by cimigree

### Description
Adds error handling for audio
Uses the Error Bottom Sheet as it is perfect for the needs here

### Instruction
Do some audio stuff and make sure everything works properly
Throw some errors...
For example, in useAudioRecording.ts in startRecording do 
```
const startRecording = useCallback(async () => {
    try {
      throw new Error('Simulated error in startRecording');

      const {recording: audioRecording} = await Audio.Recording.createAsync(
        Audio.RecordingOptionsPresets.HIGH_QUALITY,
        stat => setStatus(stat),
      );
      setRecording(audioRecording);
    } catch (err) {
      const error = normalizeError(err);
      setError(error);
    }
  }, [setRecording, setStatus, setError]);
```
Then go to make an audio recording and you will see the error.
Try it with and without a message to see each option
Another one where you can see an actual error...
Make a recording. Go to play it back...
In Playback.tsx
modify to this:
export function Playback({
  uri,
  leftControl,
  rightControl,
}: {
  uri: string;
  isModalOpen?: boolean;
  leftControl?: ReactNode;
  rightControl?: ReactNode;
}) {
  const {formatMessage: t} = useIntl();
  uri = 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3';
  const {
    duration,
    currentPosition,
    isPlaying,
    stopPlayback,
    startPlayback,
    error,
    clearError,
  } = useAudioPlayback(uri);
  
  You will see an error that looks like this:
<image src="https://github.com/user-attachments/assets/db8fefcd-c889-47ae-be30-125961493019" width="250" />

2024-10-14 18:39 UTC, ErikSin requested changes
Small changes, but otherwise looks good

2024-10-14 18:39 UTC, ErikSin commented on src/frontend/screens/Audio/CreateRecording/index.tsx
> +        }
I don't think we should add an error message. This is not translatable and any messages will need to be approved by codesign first

2024-10-14 18:39 UTC, ErikSin commented on src/frontend/screens/Audio/CreateRecording/index.tsx
> +        error={error}
I think we should throw an error if the `recordingState` is done and there is no uri:

```ts
if(recordingState === 'done' && !uri){
    setError(new Erorr('no uri'))
}

return (...rest)
```

2024-10-16 19:05 UTC, ErikSin requested changes
as i think about this i think it would make sense NOT to pass a clearError, and have the user just use the reset. If there is an error at any time during the recording, we just want to reset and have the user retry. That requires us to reset(), which encapsulates setting the error to false.

I think it also means we shouldnt pass anything to `tryAgain` in the ErrorBottom Sheet, because the goBack button will call clear error and the clear error wil call the reset, so the try again and go back will be the same.

Also, sorry this was not said before, but I think passing the Error as an Error, and not a boolean, is still the best practice. Right now we dont have a customized error message, but in the future we might want to. So passing the error to the bottom sheet is something we still want to do, but we just dont want to expose the error message right now.

2024-10-16 19:05 UTC, ErikSin commented on src/frontend/screens/Audio/CreateRecording/index.tsx
> +  }, [recordingState, uri, setHasError]);
i think we should take out this `useEffect`. Better alternative:

```ts
if(!error && recordingState === 'done' && !uri){
     setHasError(true)
}

```

2024-10-16 19:05 UTC, ErikSin commented on src/frontend/screens/Audio/CreateRecording/useAudioRecording.ts
> +      setHasError(false);
why do we need to setHasError to false here?

2024-10-16 19:05 UTC, ErikSin commented on src/frontend/screens/Audio/CreateRecording/index.tsx
> +              ? stopRecording
If it throws an error while recording, to reset, the user will call stop recording, which will set the recoding status to done which i think is undesired behaviour.

I think regardless of the state, the "try again" should reset the the recording, and have the user start again.

2024-10-17 17:59 UTC, cimigree commented
@ErikSin I didn't do the reset thing in Playback. Wasn't sure if that was warranted there as the error might just be a matter of loading timing for example and resetting would involve clearing out the uri.

2024-10-17 19:23 UTC, ErikSin approved these changes
Looks good!

2024-10-17 19:29 UTC, merged