Es/observations with core latest
digidem/CoMapeo-mobile pull request #88
Opened 2023-11-01 17:26 UTC by ErikSin

User can create, see list, and see map of observations

2023-12-14 19:55 UTC, ErikSin commented on src/frontend/screens/ManualGpsScreen/DdForm.tsx
This file has been ported over directly from mapeo.

2023-12-14 19:55 UTC, ErikSin commented on src/frontend/screens/ManualGpsScreen/DmsForm/DmsInputGroup.tsx
this file has been ported over directly from mapeo.

2023-12-14 19:55 UTC, ErikSin commented on src/frontend/screens/ManualGpsScreen/DmsForm/index.tsx
this file has been ported over directly from mapeo.

2023-12-14 19:55 UTC, ErikSin commented on src/frontend/screens/ManualGpsScreen/UtmForm.tsx
this file has been ported over directly from mapeo.

2023-12-14 19:56 UTC, ErikSin commented on src/frontend/screens/ManualGpsScreen/index.tsx
this file has been ported over directly from mapeo.

2023-12-14 19:56 UTC, ErikSin commented on src/frontend/screens/ManualGpsScreen/shared.ts
this file has been ported over directly from mapeo.

2023-12-20 18:18 UTC, achou11 requested changes
A few relatively small questions I wanted to ask before approving - overall seems like changes make sense

2023-12-20 18:18 UTC, achou11 commented on src/backend/package-lock.json
curious why there's a diff for this. there shouldn't be if none of the backend deps have changed

2024-01-18 01:21 UTC, ErikSin commented
closed as it is being replaced by #157

2024-01-18 01:21 UTC, closed without merging