chore: update backend native deps
digidem/comapeo-mobile pull request #896
Opened 2024-12-18 22:19 UTC by gmaclennan

This updates the holepunch.to managed native deps to the latest versions, using the updated prebuilds.

This also changes native module prebuilds from hard-coded versions to actually use the prebuild versions that match the dependencies.

I have tested this on in an emulator to check the app loads and I can create an observation, but I have not tested beyond that.

The dependency updates are all within semver, so there should be no breaking changes, however it would be good to update comapeo-core to the same versions and check all the tests pass.

This solves issues with these modules on x64, but x64 is still blocked by better-sqlite3 which is still broken on x64.

2025-01-22 18:06 UTC, ErikSin commented
@achou11 do you mind taking a look at this PR?

2025-01-22 18:07 UTC, achou11 commented
> @achou11 do you mind taking a look at this PR?

yeah I had started looking at it yesterday. My understanding is that we probably don't want to integrate this for the upcoming release just yet so I de-prioritized. Is that accurate?

2025-01-28 22:10 UTC, achou11 requested changes

2025-01-28 22:10 UTC, achou11 commented on scripts/build-backend.mjs
> +fs.writeFileSync('./nodejs-assets/BUILD_NATIVE_MODULES.txt', '0', {
This needs to stay enabled because it's how nmrn internally decides to look for prebuilds in the first place. Otherwise the prebuilds will not be copied into the final apk.

> I have tested this on in an emulator to check the app loads and I can create an observation, but I have not tested beyond that.

This change prevents the app from running at all for me. Were you testing in an emulator prior to making this specific change?

2025-01-28 22:10 UTC, achou11 commented on scripts/download-prebuilds.mjs
> +const TARGETS = ['android-arm', 'android-arm64', 'android-x64'];
should remove the note above

2025-01-28 22:13 UTC, achou11 commented on scripts/download-prebuilds.mjs
> +const TARGETS = ['android-arm', 'android-arm64', 'android-x64'];
addressed via 4bf1a37e66f07f97640507280b2e8efd5161f595

2025-01-28 22:13 UTC, achou11 commented on scripts/build-backend.mjs
> +fs.writeFileSync('./nodejs-assets/BUILD_NATIVE_MODULES.txt', '0', {
addressed via 473b7ef5cf6e1ad80cec8303577f29041ddbbda8

2025-01-28 22:20 UTC, achou11 approved these changes

2025-01-28 22:22 UTC, merged